### ISSUE TITLE
Check if module load is good type

### ISSUE THREAD

**Issue by AEnguerrand** [AEnguerrand/cpp_zia#78]
Example:
No load module (router, php, etc), into module Network

**Comment by Convly** [comment]
From https://stackoverflow.com/a/551124:

> You can't make that check. There is simply no way you can check whether a pointer is "valid". You have to trust that when people use a function that takes a pointer, those people know what they are doing. If they pass you 0x4211 as a pointer value, then you have to trust it points to address 0x4211.
